insert into searchtowns(id, name) values ('Amsterdam','Amsterdam');
insert into searchtowns(id, name) values ('Rotterdam','Rotterdam');
insert into searchtowns(id, name) values ('Den Haag','Den Haag');
insert into searchtowns(id, name) values ('Utrecht','Utrecht');
insert into searchtowns(id, name) values ('Eindhoven','Eindhoven');
insert into searchtowns(id, name) values ('Tilburg','Tilburg');
insert into searchtowns(id, name) values ('Groningen','Groningen');
insert into searchtowns(id, name) values ('Almere','Almere');
insert into searchtowns(id, name) values ('Breda','Breda');
insert into searchtowns(id, name) values ('Nijmegen','Nijmegen');
insert into searchtowns(id, name) values ('Enschede','Enschede');
insert into searchtowns(id, name) values ('Haarlem','Haarlem');
insert into searchtowns(id, name) values ('Arnhem','Arnhem');
insert into searchtowns(id, name) values ('Zaanstad','Zaanstad');
insert into searchtowns(id, name) values ('Amersfoort','Amersfoort');
insert into searchtowns(id, name) values ('Apeldoorn','Apeldoorn');
insert into searchtowns(id, name) values ('Den Bosch','Den Bosch');
insert into searchtowns(id, name) values ('Hoofddorp','Hoofddorp');
insert into searchtowns(id, name) values ('Maastricht','Maastricht');
insert into searchtowns(id, name) values ('Leiden','Leiden');
insert into searchtowns(id, name) values ('Dordrecht','Dordrecht');
insert into searchtowns(id, name) values ('Zoetermeer','Zoetermeer');
insert into searchtowns(id, name) values ('Zwolle','Zwolle');
insert into searchtowns(id, name) values ('Deventer','Deventer');
insert into searchtowns(id, name) values ('Born','Born');
insert into searchtowns(id, name) values ('Delft','Delft');
insert into searchtowns(id, name) values ('Alkmaar','Alkmaar');
insert into searchtowns(id, name) values ('Heerlen','Heerlen');
insert into searchtowns(id, name) values ('Venlo','Venlo');
insert into searchtowns(id, name) values ('Leeuwarden','Leeuwarden');
insert into searchtowns(id, name) values ('Amsterdam Zuidoost','Amsterdam Zuidoost');
insert into searchtowns(id, name) values ('Hilversum','Hilversum');
insert into searchtowns(id, name) values ('Hengelo ov','Hengelo ov');
insert into searchtowns(id, name) values ('Roosendaal','Roosendaal');
insert into searchtowns(id, name) values ('Purmerend','Purmerend');
insert into searchtowns(id, name) values ('Oss','Oss');
insert into searchtowns(id, name) values ('Schiedam','Schiedam');
insert into searchtowns(id, name) values ('Spijkenisse','Spijkenisse');
insert into searchtowns(id, name) values ('Helmond','Helmond');
insert into searchtowns(id, name) values ('Almelo','Almelo');
insert into searchtowns(id, name) values ('Gouda','Gouda');
insert into searchtowns(id, name) values ('Lelystad','Lelystad');
insert into searchtowns(id, name) values ('Alphen a/d Rijn','Alphen a/d Rijn');
insert into searchtowns(id, name) values ('Hoorn nh','Hoorn nh');
insert into searchtowns(id, name) values ('Velsen-Zuid','Velsen-Zuid');
insert into searchtowns(id, name) values ('Bergen op Zoom','Bergen op Zoom');
insert into searchtowns(id, name) values ('Capelle aan den IJssel','Capelle aan den IJssel');
insert into searchtowns(id, name) values ('Assen','Assen');
insert into searchtowns(id, name) values ('Veenendaal','Veenendaal');
insert into searchtowns(id, name) values ('Zeist','Zeist');
insert into searchtowns(id, name) values ('Den Helder','Den Helder');
insert into searchtowns(id, name) values ('Hardenberg','Hardenberg');
insert into searchtowns(id, name) values ('Emmen','Emmen');
insert into searchtowns(id, name) values ('Oosterhout nb','Oosterhout nb');
insert into searchtowns(id, name) values ('Doetinchem','Doetinchem');
insert into searchtowns(id, name) values ('Kerkrade','Kerkrade');
insert into searchtowns(id, name) values ('Kampen','Kampen');
insert into searchtowns(id, name) values ('Weert','Weert');
insert into searchtowns(id, name) values ('Woerden','Woerden');
insert into searchtowns(id, name) values ('Heerhugowaard','Heerhugowaard');
insert into searchtowns(id, name) values ('Middelburg','Middelburg');
insert into searchtowns(id, name) values ('Emmeloord','Emmeloord');
insert into searchtowns(id, name) values ('Waalwijk','Waalwijk');
insert into searchtowns(id, name) values ('Soest','Soest');
insert into searchtowns(id, name) values ('Roermond','Roermond');
insert into searchtowns(id, name) values ('Drachten','Drachten');
insert into searchtowns(id, name) values ('Heerenveen','Heerenveen');
insert into searchtowns(id, name) values ('Tiel','Tiel');
insert into searchtowns(id, name) values ('Harderwijk','Harderwijk');
insert into searchtowns(id, name) values ('Maarssen','Maarssen');
insert into searchtowns(id, name) values ('Venray','Venray');
insert into searchtowns(id, name) values ('Hoogeveen','Hoogeveen');
insert into searchtowns(id, name) values ('Barendrecht','Barendrecht');
insert into searchtowns(id, name) values ('Dronten','Dronten');
insert into searchtowns(id, name) values ('Goes','Goes');
insert into searchtowns(id, name) values ('Zutphen','Zutphen');
insert into searchtowns(id, name) values ('Wageningen','Wageningen');
insert into searchtowns(id, name) values ('Castricum','Castricum');
insert into searchtowns(id, name) values ('Gorinchem','Gorinchem');
insert into searchtowns(id, name) values ('Uden','Uden');
insert into searchtowns(id, name) values ('Mijdrecht','Mijdrecht');
insert into searchtowns(id, name) values ('IJsselstein ut','IJsselstein ut');
insert into searchtowns(id, name) values ('Epe','Epe');
insert into searchtowns(id, name) values ('Sneek','Sneek');
insert into searchtowns(id, name) values ('Maassluis','Maassluis');
insert into searchtowns(id, name) values ('Wijchen','Wijchen');
insert into searchtowns(id, name) values ('Oldenzaal','Oldenzaal');
insert into searchtowns(id, name) values ('Valkenswaard','Valkenswaard');
insert into searchtowns(id, name) values ('Meppel','Meppel');
insert into searchtowns(id, name) values ('Winterswijk','Winterswijk');
insert into searchtowns(id, name) values ('Boxtel','Boxtel');
insert into searchtowns(id, name) values ('Best','Best');
insert into searchtowns(id, name) values ('Delfzijl','Delfzijl');
insert into searchtowns(id, name) values ('Barneveld','Barneveld');
insert into searchtowns(id, name) values ('Veendam','Veendam');
insert into searchtowns(id, name) values ('Terneuzen','Terneuzen');
insert into searchtowns(id, name) values ('Geldrop','Geldrop');
insert into searchtowns(id, name) values ('Culemborg','Culemborg');
insert into searchtowns(id, name) values ('Drimmelen','Drimmelen');
insert into searchtowns(id, name) values ('Dalfsen','Dalfsen');
insert into searchtowns(id, name) values ('Zaltbommel','Zaltbommel');
insert into searchtowns(id, name) values ('Werkendam','Werkendam');
insert into searchtowns(id, name) values ('Borger','Borger');
insert into searchtowns(id, name) values ('Zevenaar','Zevenaar');
insert into searchtowns(id, name) values ('Oisterwijk','Oisterwijk');
insert into searchtowns(id, name) values ('Geldermalsen','Geldermalsen');
insert into searchtowns(id, name) values ('Wolvega','Wolvega');
insert into searchtowns(id, name) values ('Dongen','Dongen');
insert into searchtowns(id, name) values ('Wassenaar','Wassenaar');
insert into searchtowns(id, name) values ('Veghel','Veghel');
insert into searchtowns(id, name) values ('Anloo','Anloo');
insert into searchtowns(id, name) values ('Noordwijk zh','Noordwijk zh');
insert into searchtowns(id, name) values ('Haaksbergen','Haaksbergen');
insert into searchtowns(id, name) values ('Cuijk','Cuijk');
insert into searchtowns(id, name) values ('Sliedrecht','Sliedrecht');
insert into searchtowns(id, name) values ('Wijk bij Duurstede','Wijk bij Duurstede');
insert into searchtowns(id, name) values ('Steenbergen nb','Steenbergen nb');
insert into searchtowns(id, name) values ('Schijndel','Schijndel');
insert into searchtowns(id, name) values ('Putten','Putten');
insert into searchtowns(id, name) values ('Oldebroek','Oldebroek');
insert into searchtowns(id, name) values ('Aalsmeer','Aalsmeer');
insert into searchtowns(id, name) values ('Rucphen','Rucphen');
insert into searchtowns(id, name) values ('Losser','Losser');
insert into searchtowns(id, name) values ('Borssele','Borssele');
insert into searchtowns(id, name) values ('Lisse','Lisse');
insert into searchtowns(id, name) values ('Volendam','Volendam');
insert into searchtowns(id, name) values ('Hellevoetsluis','Hellevoetsluis');
insert into searchtowns(id, name) values ('Hoogezand','Hoogezand');
insert into searchtowns(id, name) values ('Leerdam','Leerdam');
insert into searchtowns(id, name) values ('Gendringen','Gendringen');
insert into searchtowns(id, name) values ('Zundert','Zundert');
insert into searchtowns(id, name) values ('Tubbergen','Tubbergen');
insert into searchtowns(id, name) values ('Raalte','Raalte');
insert into searchtowns(id, name) values ('Stadskanaal','Stadskanaal');
insert into searchtowns(id, name) values ('Leek','Leek');
insert into searchtowns(id, name) values ('Lichtenvoorde','Lichtenvoorde');
insert into searchtowns(id, name) values ('Nunspeet','Nunspeet');
insert into searchtowns(id, name) values ('Bladel','Bladel');
insert into searchtowns(id, name) values ('Zeewolde','Zeewolde');
insert into searchtowns(id, name) values ('Schagen','Schagen');
insert into searchtowns(id, name) values ('Winschoten','Winschoten');
insert into searchtowns(id, name) values ('Eersel','Eersel');
insert into searchtowns(id, name) values ('Someren','Someren');
insert into searchtowns(id, name) values ('Druten','Druten');
insert into searchtowns(id, name) values ('Naaldwijk','Naaldwijk');
insert into searchtowns(id, name) values ('Middelharnis','Middelharnis');
insert into searchtowns(id, name) values ('Enkhuizen','Enkhuizen');
insert into searchtowns(id, name) values ('Urk','Urk');
insert into searchtowns(id, name) values ('Vlagtwedde','Vlagtwedde');
insert into searchtowns(id, name) values ('Steenwijk','Steenwijk');
insert into searchtowns(id, name) values ('Zandvoort','Zandvoort');
insert into searchtowns(id, name) values ('Gennep','Gennep');
insert into searchtowns(id, name) values ('Eibergen','Eibergen');
insert into searchtowns(id, name) values ('Harlingen','Harlingen');
insert into searchtowns(id, name) values ('Nuth','Nuth');
insert into searchtowns(id, name) values ('Hilvarenbeek','Hilvarenbeek');
insert into searchtowns(id, name) values ('Dieren','Dieren');
insert into searchtowns(id, name) values ('Coevorden','Coevorden');
insert into searchtowns(id, name) values ('Lopik','Lopik');
insert into searchtowns(id, name) values ('Maasbracht','Maasbracht');
insert into searchtowns(id, name) values ('Margraten','Margraten');
insert into searchtowns(id, name) values ('Dokkum','Dokkum');
insert into searchtowns(id, name) values ('Franeker','Franeker');
insert into searchtowns(id, name) values ('Joure','Joure');
insert into searchtowns(id, name) values ('Maasbree','Maasbree');
insert into searchtowns(id, name) values ('Lochem','Lochem');
insert into searchtowns(id, name) values ('Schoonhoven','Schoonhoven');
insert into searchtowns(id, name) values ('Klazienaveen','Klazienaveen');
insert into searchtowns(id, name) values ('Grootegast','Grootegast');
insert into searchtowns(id, name) values ('Goedereede','Goedereede');
insert into searchtowns(id, name) values ('Goor','Goor');
insert into searchtowns(id, name) values ('Ulrum','Ulrum');
insert into searchtowns(id, name) values ('Opmeer','Opmeer');
insert into searchtowns(id, name) values ('Nieuwkoop','Nieuwkoop');
insert into searchtowns(id, name) values ('Hulst','Hulst');
insert into searchtowns(id, name) values ('Bedum','Bedum');
insert into searchtowns(id, name) values ('Leimuiden','Leimuiden');
insert into searchtowns(id, name) values ('Borculo','Borculo');
insert into searchtowns(id, name) values ('Vaals','Vaals');
insert into searchtowns(id, name) values ('Bergum','Bergum');
insert into searchtowns(id, name) values ('Lemmer','Lemmer');
insert into searchtowns(id, name) values ('Strijen','Strijen');
insert into searchtowns(id, name) values ('Blaricum','Blaricum');
insert into searchtowns(id, name) values ('Bolsward','Bolsward');
insert into searchtowns(id, name) values ('Arcen','Arcen');
insert into searchtowns(id, name) values ('Vroomshoop','Vroomshoop');
insert into searchtowns(id, name) values ('Axel','Axel');
insert into searchtowns(id, name) values ('Emmer-Compascuum','Emmer-Compascuum');
insert into searchtowns(id, name) values ('Leersum','Leersum');
insert into searchtowns(id, name) values ('Rheden','Rheden');
insert into searchtowns(id, name) values ('Hasselt','Hasselt');
insert into searchtowns(id, name) values ('Delden','Delden');
insert into searchtowns(id, name) values ('Gorredijk','Gorredijk');
insert into searchtowns(id, name) values ('Schaijk','Schaijk');
insert into searchtowns(id, name) values ('Yerseke','Yerseke');
insert into searchtowns(id, name) values ('Heythuysen','Heythuysen');
insert into searchtowns(id, name) values ('Den Burg','Den Burg');
insert into searchtowns(id, name) values ('Klundert','Klundert');
insert into searchtowns(id, name) values ('Varsseveld','Varsseveld');
insert into searchtowns(id, name) values ('Aalburg','Aalburg');
insert into searchtowns(id, name) values ('Buitenpost','Buitenpost');
insert into searchtowns(id, name) values ('Grou','Grou');
insert into searchtowns(id, name) values ('Wijhe','Wijhe');
insert into searchtowns(id, name) values ('Heteren','Heteren');
insert into searchtowns(id, name) values ('Bergen aan Zee','Bergen aan Zee');
insert into searchtowns(id, name) values ('Bergen nh','Bergen nh');
insert into searchtowns(id, name) values ('Schoonebeek','Schoonebeek');
insert into searchtowns(id, name) values ('Schinveld','Schinveld');
insert into searchtowns(id, name) values ('Kootwijkerbroek','Kootwijkerbroek');
insert into searchtowns(id, name) values ('Haamstede','Haamstede');
insert into searchtowns(id, name) values ('Posterholt','Posterholt');
insert into searchtowns(id, name) values ('Wetering','Wetering');
insert into searchtowns(id, name) values ('Bruinisse','Bruinisse');
insert into searchtowns(id, name) values ('Workum','Workum');
insert into searchtowns(id, name) values ('Sas van Gent','Sas van Gent');
insert into searchtowns(id, name) values ('Vollenhove','Vollenhove');
insert into searchtowns(id, name) values ('Noordwolde fr','Noordwolde fr');
insert into searchtowns(id, name) values ('Bunschoten-Spakenburg','Bunschoten-Spakenburg');
insert into searchtowns(id, name) values ('Buinen','Buinen');
insert into searchtowns(id, name) values ('Markelo','Markelo');
insert into searchtowns(id, name) values ('Balk','Balk');
insert into searchtowns(id, name) values ('Makkum fr','Makkum fr');
insert into searchtowns(id, name) values ('Dronrijp','Dronrijp');
insert into searchtowns(id, name) values ('Harskamp','Harskamp');
insert into searchtowns(id, name) values ('Middelbeers','Middelbeers');
insert into searchtowns(id, name) values ('Lienden','Lienden');
insert into searchtowns(id, name) values ('Ens','Ens');
insert into searchtowns(id, name) values ('Havelte','Havelte');
insert into searchtowns(id, name) values ('Hallum','Hallum');
insert into searchtowns(id, name) values ('Beesel','Beesel');
insert into searchtowns(id, name) values ('Terschelling','Terschelling');
insert into searchtowns(id, name) values ('Moerdijk','Moerdijk');
insert into searchtowns(id, name) values ('Willemstad nb','Willemstad nb');
insert into searchtowns(id, name) values ('Aduard','Aduard');
insert into searchtowns(id, name) values ('Sleen','Sleen');
insert into searchtowns(id, name) values ('Den Oever','Den Oever');
insert into searchtowns(id, name) values ('Giekerk','Giekerk');
insert into searchtowns(id, name) values ('Garderen','Garderen');
insert into searchtowns(id, name) values ('Odiliapeel','Odiliapeel');
insert into searchtowns(id, name) values ('Oerle','Oerle');
insert into searchtowns(id, name) values ('Medemblik','Medemblik');
insert into searchtowns(id, name) values ('Tynaarlo','Tynaarlo');
insert into searchtowns(id, name) values ('Echt','Echt');
insert into searchtowns(id, name) values ('Harfsen','Harfsen');
insert into searchtowns(id, name) values ('Holwerd','Holwerd');
insert into searchtowns(id, name) values ('Vreeland','Vreeland');
insert into searchtowns(id, name) values ('Aldeboarn','Aldeboarn');
insert into searchtowns(id, name) values ('Scharendijke','Scharendijke');
insert into searchtowns(id, name) values ('Zwartebroek','Zwartebroek');
insert into searchtowns(id, name) values ('Hollum','Hollum');
insert into searchtowns(id, name) values ('Echtenerbrug','Echtenerbrug');
insert into searchtowns(id, name) values ('Anjum','Anjum');
insert into searchtowns(id, name) values ('Mantgum','Mantgum');
insert into searchtowns(id, name) values ('Ameland','Ameland');
insert into searchtowns(id, name) values ('Vlieland','Vlieland');
insert into searchtowns(id, name) values ('Warten','Warten');
insert into searchtowns(id, name) values ('Stavoren','Stavoren');
insert into searchtowns(id, name) values ('Meers','Meers');
insert into searchtowns(id, name) values ('Schiermonnikoog','Schiermonnikoog');
insert into searchtowns(id, name) values ('Lijnden','Lijnden');
insert into searchtowns(id, name) values ('Siegerswoude','Siegerswoude');
insert into searchtowns(id, name) values ('Hoornsterzwaag','Hoornsterzwaag');
insert into searchtowns(id, name) values ('Boerdonk','Boerdonk');
insert into searchtowns(id, name) values ('Hoenderloo','Hoenderloo');
insert into searchtowns(id, name) values ('Tilligte','Tilligte');
insert into searchtowns(id, name) values ('Geesbrug','Geesbrug');
insert into searchtowns(id, name) values ('Empe','Empe');
insert into searchtowns(id, name) values ('Elsloo fr','Elsloo fr');
insert into searchtowns(id, name) values ('Nieuwvliet','Nieuwvliet');
insert into searchtowns(id, name) values ('Laag Zuthem','Laag Zuthem');
insert into searchtowns(id, name) values ('Lieveren','Lieveren');
insert into searchtowns(id, name) values ('Bunne','Bunne');
insert into searchtowns(id, name) values ('Hoog Soeren','Hoog Soeren');
insert into searchtowns(id, name) values ('Smalle Ee','Smalle Ee');
insert into searchtowns(id, name) values ('Zuidzijde','Zuidzijde');
insert into searchtowns(id, name) values ('Edens','Edens');
insert into searchtowns(id, name) values ('Jipsingboermussel','Jipsingboermussel');
insert into searchtowns(id, name) values ('Aagtekerke','Aagtekerke');
insert into searchtowns(id, name) values ('Aalden','Aalden');
insert into searchtowns(id, name) values ('Aalst gld','Aalst gld');
insert into searchtowns(id, name) values ('Aardenburg','Aardenburg');
insert into searchtowns(id, name) values ('Achtkarspelen gem bestuur','Achtkarspelen gem bestuur');
insert into searchtowns(id, name) values ('Afferden gld','Afferden gld');
insert into searchtowns(id, name) values ('Afferden lb','Afferden lb');
insert into searchtowns(id, name) values ('Aijen','Aijen');
insert into searchtowns(id, name) values ('Alem','Alem');
insert into searchtowns(id, name) values ('Alkemade gem bestuur','Alkemade gem bestuur');
insert into searchtowns(id, name) values ('Alkmaar Noord','Alkmaar Noord');
insert into searchtowns(id, name) values ('Almere Centrum','Almere Centrum');
insert into searchtowns(id, name) values ('Almere Muziekwijk','Almere Muziekwijk');
insert into searchtowns(id, name) values ('Almere Oostvaarders','Almere Oostvaarders');
insert into searchtowns(id, name) values ('Almere Parkwijk','Almere Parkwijk');
insert into searchtowns(id, name) values ('Almere Strand','Almere Strand');
insert into searchtowns(id, name) values ('Alphen gld','Alphen gld');
insert into searchtowns(id, name) values ('Alphen nb','Alphen nb');
insert into searchtowns(id, name) values ('Alteveer gem Hoogeveen','Alteveer gem Hoogeveen');
insert into searchtowns(id, name) values ('Alteveer gem Noordenveld','Alteveer gem Noordenveld');
insert into searchtowns(id, name) values ('Alteveer gem de Wolden','Alteveer gem de Wolden');
insert into searchtowns(id, name) values ('Alteveer gn','Alteveer gn');
insert into searchtowns(id, name) values ('Ambt Delden','Ambt Delden');
insert into searchtowns(id, name) values ('America','America');
insert into searchtowns(id, name) values ('Amsterdam Centraal','Amsterdam Centraal');
insert into searchtowns(id, name) values ('Amsterdam Centraal Station','Amsterdam Centraal Station');
insert into searchtowns(id, name) values ('Andijk','Andijk');
insert into searchtowns(id, name) values ('Ankeveen','Ankeveen');
insert into searchtowns(id, name) values ('Anna Paulowna','Anna Paulowna');
insert into searchtowns(id, name) values ('Annerveensche Kanaal','Annerveensche Kanaal');
insert into searchtowns(id, name) values ('Appelscha','Appelscha');
insert into searchtowns(id, name) values ('Archem','Archem');
insert into searchtowns(id, name) values ('Arriën','Arriën');
insert into searchtowns(id, name) values ('Arriërveld','Arriërveld');
insert into searchtowns(id, name) values ('Austerlitz','Austerlitz');
insert into searchtowns(id, name) values ('Avenhorn','Avenhorn');
insert into searchtowns(id, name) values ('Avereest gem bestuur','Avereest gem bestuur');
insert into searchtowns(id, name) values ('Baarland','Baarland');
insert into searchtowns(id, name) values ('Baarlo lb','Baarlo lb');
insert into searchtowns(id, name) values ('Babyloniënbroek','Babyloniënbroek');
insert into searchtowns(id, name) values ('Baflo','Baflo');
insert into searchtowns(id, name) values ('Bakhuizen','Bakhuizen');
insert into searchtowns(id, name) values ('Balkbrug','Balkbrug');
insert into searchtowns(id, name) values ('Balloërveld','Balloërveld');
insert into searchtowns(id, name) values ('Bartlehiem gem Ferwerderadiel','Bartlehiem gem Ferwerderadiel');
insert into searchtowns(id, name) values ('Bartlehiem gem Tietjerksteradeel','Bartlehiem gem Tietjerksteradeel');
insert into searchtowns(id, name) values ('Bath','Bath');
insert into searchtowns(id, name) values ('Bavel ac','Bavel ac');
insert into searchtowns(id, name) values ('Bears fr','Bears fr');
insert into searchtowns(id, name) values ('Beatrixpark Amsterdam','Beatrixpark Amsterdam');
insert into searchtowns(id, name) values ('Beek en Donk','Beek en Donk');
insert into searchtowns(id, name) values ('Beek gem Montferland','Beek gem Montferland');
insert into searchtowns(id, name) values ('Beek lb','Beek lb');
insert into searchtowns(id, name) values ('Beemster gem bestuur','Beemster gem bestuur');
insert into searchtowns(id, name) values ('Beemte Broekland','Beemte Broekland');
insert into searchtowns(id, name) values ('Beerta','Beerta');
insert into searchtowns(id, name) values ('Beilen','Beilen');
insert into searchtowns(id, name) values ('Bekveld','Bekveld');
insert into searchtowns(id, name) values ('Bellingwedde gem bestuur','Bellingwedde gem bestuur');
insert into searchtowns(id, name) values ('Belt-Schutsloot','Belt-Schutsloot');
insert into searchtowns(id, name) values ('Berg en Terblijt','Berg en Terblijt');
insert into searchtowns(id, name) values ('Bergen lb','Bergen lb');
insert into searchtowns(id, name) values ('Beringe','Beringe');
insert into searchtowns(id, name) values ('Bernheze gem bestuur','Bernheze gem bestuur');
insert into searchtowns(id, name) values ('Beuningen gld','Beuningen gld');
insert into searchtowns(id, name) values ('Biervliet','Biervliet');
insert into searchtowns(id, name) values ('Binnenmaas gem bestuur','Binnenmaas gem bestuur');
insert into searchtowns(id, name) values ('Binnenwijzend','Binnenwijzend');
insert into searchtowns(id, name) values ('Blankenham','Blankenham');
insert into searchtowns(id, name) values ('Blauwestad','Blauwestad');
insert into searchtowns(id, name) values ('Blitterswijck','Blitterswijck');
insert into searchtowns(id, name) values ('Boarnsterhim gem bestuur','Boarnsterhim gem bestuur');
insert into searchtowns(id, name) values ('Boer','Boer');
insert into searchtowns(id, name) values ('Boerakker gem Leek','Boerakker gem Leek');
insert into searchtowns(id, name) values ('Borgsweer','Borgsweer');
insert into searchtowns(id, name) values ('Borkel en Schaft','Borkel en Schaft');
insert into searchtowns(id, name) values ('Botlek rt','Botlek rt');
insert into searchtowns(id, name) values ('Bourtange','Bourtange');
insert into searchtowns(id, name) values ('Bovenkerk','Bovenkerk');
insert into searchtowns(id, name) values ('Bovensmilde','Bovensmilde');
insert into searchtowns(id, name) values ('Breezand','Breezand');
insert into searchtowns(id, name) values ('Breezanddijk','Breezanddijk');
insert into searchtowns(id, name) values ('Breskens','Breskens');
insert into searchtowns(id, name) values ('Broekhuizen lb','Broekhuizen lb');
insert into searchtowns(id, name) values ('Bruinehaar','Bruinehaar');
insert into searchtowns(id, name) values ('Bruntinge','Bruntinge');
insert into searchtowns(id, name) values ('Budel','Budel');
insert into searchtowns(id, name) values ('Buinerveen','Buinerveen');
insert into searchtowns(id, name) values ('Buren gld','Buren gld');
insert into searchtowns(id, name) values ('Burgh-Haamstede','Burgh-Haamstede');
insert into searchtowns(id, name) values ('Buurse','Buurse');
insert into searchtowns(id, name) values ('Callantsoog','Callantsoog');
insert into searchtowns(id, name) values ('Camerig','Camerig');
insert into searchtowns(id, name) values ('Castelré','Castelré');
insert into searchtowns(id, name) values ('Centraal Station','Centraal Station');
insert into searchtowns(id, name) values ('Centraal Station Amsterdam','Centraal Station Amsterdam');
insert into searchtowns(id, name) values ('Chèvremont','Chèvremont');
insert into searchtowns(id, name) values ('Colijnsplaat','Colijnsplaat');
insert into searchtowns(id, name) values ('Cranendonck gem bestuur','Cranendonck gem bestuur');
insert into searchtowns(id, name) values ('Creil','Creil');
insert into searchtowns(id, name) values ('Cromstrijen gem bestuur','Cromstrijen gem bestuur');
insert into searchtowns(id, name) values ('Cromvoirt','Cromvoirt');
insert into searchtowns(id, name) values ('Dantumadeel gem bestuur','Dantumadeel gem bestuur');
insert into searchtowns(id, name) values ('De Cocksdorp','De Cocksdorp');
insert into searchtowns(id, name) values ('De Haukes','De Haukes');
insert into searchtowns(id, name) values ('De Hoek','De Hoek');
insert into searchtowns(id, name) values ('De Klencke','De Klencke');
insert into searchtowns(id, name) values ('De Marne gem bestuur','De Marne gem bestuur');
insert into searchtowns(id, name) values ('De Rijp','De Rijp');
insert into searchtowns(id, name) values ('De Rips','De Rips');
insert into searchtowns(id, name) values ('De Stapel','De Stapel');
insert into searchtowns(id, name) values ('De Wilp gn','De Wilp gn');
insert into searchtowns(id, name) values ('Den Ham gn','Den Ham gn');
insert into searchtowns(id, name) values ('Den Hulst gem Staphorst','Den Hulst gem Staphorst');
insert into searchtowns(id, name) values ('Deurne','Deurne');
insert into searchtowns(id, name) values ('Diever','Diever');
insert into searchtowns(id, name) values ('Dijken','Dijken');
insert into searchtowns(id, name) values ('Dijkerhoek','Dijkerhoek');
insert into searchtowns(id, name) values ('Dinxperlo','Dinxperlo');
insert into searchtowns(id, name) values ('Dongeradeel gem bestuur','Dongeradeel gem bestuur');
insert into searchtowns(id, name) values ('Donk lb','Donk lb');
insert into searchtowns(id, name) values ('Doornenburg','Doornenburg');
insert into searchtowns(id, name) values ('Dreischor','Dreischor');
insert into searchtowns(id, name) values ('Drempt','Drempt');
insert into searchtowns(id, name) values ('Driebruggen','Driebruggen');
insert into searchtowns(id, name) values ('Drogteropslagen','Drogteropslagen');
insert into searchtowns(id, name) values ('Dussen','Dussen');
insert into searchtowns(id, name) values ('Earnewâld','Earnewâld');
insert into searchtowns(id, name) values ('Easterein gem Littenseradiel','Easterein gem Littenseradiel');
insert into searchtowns(id, name) values ('Ede gld','Ede gld');
insert into searchtowns(id, name) values ('Eede zld','Eede zld');
insert into searchtowns(id, name) values ('Eemshaven','Eemshaven');
insert into searchtowns(id, name) values ('Eemsmond gem bestuur','Eemsmond gem bestuur');
insert into searchtowns(id, name) values ('Een-West','Een-West');
insert into searchtowns(id, name) values ('Eenum','Eenum');
insert into searchtowns(id, name) values ('Eerste Exloërmond','Eerste Exloërmond');
insert into searchtowns(id, name) values ('Eexterveen','Eexterveen');
insert into searchtowns(id, name) values ('Eexterveensche Kanaal','Eexterveensche Kanaal');
insert into searchtowns(id, name) values ('Egmondermeer','Egmondermeer');
insert into searchtowns(id, name) values ('Ell','Ell');
insert into searchtowns(id, name) values ('Elp','Elp');
insert into searchtowns(id, name) values ('Elsloo lb','Elsloo lb');
insert into searchtowns(id, name) values ('Elspeet','Elspeet');
insert into searchtowns(id, name) values ('Elst gld','Elst gld');
insert into searchtowns(id, name) values ('Engelbert','Engelbert');
insert into searchtowns(id, name) values ('Eppenhuizen','Eppenhuizen');
insert into searchtowns(id, name) values ('Etten gld','Etten gld');
insert into searchtowns(id, name) values ('Etten-Leur','Etten-Leur');
insert into searchtowns(id, name) values ('Europoort rt','Europoort rt');
insert into searchtowns(id, name) values ('Eursinge gem Midden-Drenthe','Eursinge gem Midden-Drenthe');
insert into searchtowns(id, name) values ('Eursinge gem de Wolden','Eursinge gem de Wolden');
insert into searchtowns(id, name) values ('Exloërmond Eerste','Exloërmond Eerste');
insert into searchtowns(id, name) values ('Exloërmond Tweede','Exloërmond Tweede');
insert into searchtowns(id, name) values ('Exloërveen','Exloërveen');
insert into searchtowns(id, name) values ('Ferwerd','Ferwerd');
insert into searchtowns(id, name) values ('Ferwerderadiel gem bestuur','Ferwerderadiel gem bestuur');
insert into searchtowns(id, name) values ('Formerum','Formerum');
insert into searchtowns(id, name) values ('Franekeradeel gem bestuur','Franekeradeel gem bestuur');
insert into searchtowns(id, name) values ('Gaasterlân Sleat gem bestuur','Gaasterlân Sleat gem bestuur');
insert into searchtowns(id, name) values ('Gassel','Gassel');
insert into searchtowns(id, name) values ('Geersdijk','Geersdijk');
insert into searchtowns(id, name) values ('Geesteren gld','Geesteren gld');
insert into searchtowns(id, name) values ('Geeuwenbrug gem Diever','Geeuwenbrug gem Diever');
insert into searchtowns(id, name) values ('Gelderingen','Gelderingen');
insert into searchtowns(id, name) values ('Gilze','Gilze');
insert into searchtowns(id, name) values ('Gortel','Gortel');
insert into searchtowns(id, name) values ('Graafstroom gem bestuur','Graafstroom gem bestuur');
insert into searchtowns(id, name) values ('Griendtsveen','Griendtsveen');
insert into searchtowns(id, name) values ('Groetpolder','Groetpolder');
insert into searchtowns(id, name) values ('Haarle gem Hellendoorn','Haarle gem Hellendoorn');
insert into searchtowns(id, name) values ('Haarle gem Tubbergen','Haarle gem Tubbergen');
insert into searchtowns(id, name) values ('Haarlem Station','Haarlem Station');
insert into searchtowns(id, name) values ('Haarlemmermeer gem bestuur','Haarlemmermeer gem bestuur');
insert into searchtowns(id, name) values ('Haart','Haart');
insert into searchtowns(id, name) values ('Hagestein','Hagestein');
insert into searchtowns(id, name) values ('Halderberge gem bestuur','Halderberge gem bestuur');
insert into searchtowns(id, name) values ('Hank','Hank');
insert into searchtowns(id, name) values ('Haren gn','Haren gn');
insert into searchtowns(id, name) values ('Harenkarspel gem bestuur','Harenkarspel gem bestuur');
insert into searchtowns(id, name) values ('Hattemerbroek','Hattemerbroek');
insert into searchtowns(id, name) values ('Heeswijk-Dinther','Heeswijk-Dinther');
insert into searchtowns(id, name) values ('Hei- en Boeicop','Hei- en Boeicop');
insert into searchtowns(id, name) values ('Heidenskip It','Heidenskip It');
insert into searchtowns(id, name) values ('Heilig Land-Stichting','Heilig Land-Stichting');
insert into searchtowns(id, name) values ('Heinkenszand','Heinkenszand');
insert into searchtowns(id, name) values ('Hellendoorn','Hellendoorn');
insert into searchtowns(id, name) values ('Hellum','Hellum');
insert into searchtowns(id, name) values ('Hengelo gld','Hengelo gld');
insert into searchtowns(id, name) values ('Hengstdijk','Hengstdijk');
insert into searchtowns(id, name) values ('Het Bildt gem bestuur','Het Bildt gem bestuur');
insert into searchtowns(id, name) values ('Het Koegras','Het Koegras');
insert into searchtowns(id, name) values ('Het Schouw','Het Schouw');
insert into searchtowns(id, name) values ('Heurne gem Aalten','Heurne gem Aalten');
insert into searchtowns(id, name) values ('Heurne gem Ruurlo','Heurne gem Ruurlo');
insert into searchtowns(id, name) values ('Heusden gem Asten','Heusden gem Asten');
insert into searchtowns(id, name) values ('Heusden gem Heusden','Heusden gem Heusden');
insert into searchtowns(id, name) values ('Hijlaard','Hijlaard');
insert into searchtowns(id, name) values ('Hogebeintum','Hogebeintum');
insert into searchtowns(id, name) values ('Holterberg','Holterberg');
insert into searchtowns(id, name) values ('Hooge Mierde','Hooge Mierde');
insert into searchtowns(id, name) values ('Hoogmade','Hoogmade');
insert into searchtowns(id, name) values ('Hoogvliet rt','Hoogvliet rt');
insert into searchtowns(id, name) values ('Horst lb','Horst lb');
insert into searchtowns(id, name) values ('Hout lb','Hout lb');
insert into searchtowns(id, name) values ('Huijbergen','Huijbergen');
insert into searchtowns(id, name) values ('Huins','Huins');
insert into searchtowns(id, name) values ('Huis ter Heide dr','Huis ter Heide dr');
insert into searchtowns(id, name) values ('Hulsen lb','Hulsen lb');
insert into searchtowns(id, name) values ('Idzega','Idzega');
insert into searchtowns(id, name) values ('It Heidenskip','It Heidenskip');
insert into searchtowns(id, name) values ('Jacobswoude gem bestuur','Jacobswoude gem bestuur');
insert into searchtowns(id, name) values ('Jonkerslân','Jonkerslân');
insert into searchtowns(id, name) values ('Kampereiland','Kampereiland');
insert into searchtowns(id, name) values ('Kamperzeedijk','Kamperzeedijk');
insert into searchtowns(id, name) values ('Kapel-Avezaath gem Buren','Kapel-Avezaath gem Buren');
insert into searchtowns(id, name) values ('Kerk-Avezaath gem Tiel','Kerk-Avezaath gem Tiel');
insert into searchtowns(id, name) values ('Kessel lb','Kessel lb');
insert into searchtowns(id, name) values ('Kijkuit gem Axel','Kijkuit gem Axel');
insert into searchtowns(id, name) values ('Kleine Huisjes','Kleine Huisjes');
insert into searchtowns(id, name) values ('Kockengen','Kockengen');
insert into searchtowns(id, name) values ('Kogerpolder','Kogerpolder');
insert into searchtowns(id, name) values ('Kolhorn','Kolhorn');
insert into searchtowns(id, name) values ('Kollumerland ca gem bestuur','Kollumerland ca gem bestuur');
insert into searchtowns(id, name) values ('Korendijk gem bestuur','Korendijk gem bestuur');
insert into searchtowns(id, name) values ('Koudekerke zld','Koudekerke zld');
insert into searchtowns(id, name) values ('Krommeniedijk','Krommeniedijk');
insert into searchtowns(id, name) values ('Laarbeek gem bestuur','Laarbeek gem bestuur');
insert into searchtowns(id, name) values ('Lambertschaag','Lambertschaag');
insert into searchtowns(id, name) values ('Landerd gem bestuur','Landerd gem bestuur');
insert into searchtowns(id, name) values ('Langedijk gem bestuur','Langedijk gem bestuur');
insert into searchtowns(id, name) values ('Laren gld','Laren gld');
insert into searchtowns(id, name) values ('Lattrop-Breklenkamp','Lattrop-Breklenkamp');
insert into searchtowns(id, name) values ('Leeuwarderadeel gem bestuur','Leeuwarderadeel gem bestuur');
insert into searchtowns(id, name) values ('Lemelerveld','Lemelerveld');
insert into searchtowns(id, name) values ('Lemsterland gem bestuur','Lemsterland gem bestuur');
insert into searchtowns(id, name) values ('Lengel','Lengel');
insert into searchtowns(id, name) values ('Leons','Leons');
insert into searchtowns(id, name) values ('Leur gld','Leur gld');
insert into searchtowns(id, name) values ('Lheebroek','Lheebroek');
insert into searchtowns(id, name) values ('Lichtmis','Lichtmis');
insert into searchtowns(id, name) values ('Liemeer gem bestuur','Liemeer gem bestuur');
insert into searchtowns(id, name) values ('Linde gem Diepenveen','Linde gem Diepenveen');
insert into searchtowns(id, name) values ('Linde gld','Linde gld');
insert into searchtowns(id, name) values ('Lingewaal gem bestuur','Lingewaal gem bestuur');
insert into searchtowns(id, name) values ('Lith','Lith');
insert into searchtowns(id, name) values ('Littenseradeel gem bestuur','Littenseradeel gem bestuur');
insert into searchtowns(id, name) values ('Littenseradiel gem bestuur','Littenseradiel gem bestuur');
insert into searchtowns(id, name) values ('Lobith','Lobith');
insert into searchtowns(id, name) values ('Loenen gem Valburg','Loenen gem Valburg');
insert into searchtowns(id, name) values ('Loenen gld','Loenen gld');
insert into searchtowns(id, name) values ('Loerbeek','Loerbeek');
insert into searchtowns(id, name) values ('Loo gld','Loo gld');
insert into searchtowns(id, name) values ('Loo ov','Loo ov');
insert into searchtowns(id, name) values ('Luchthaven Schiphol','Luchthaven Schiphol');
insert into searchtowns(id, name) values ('Maarheeze','Maarheeze');
insert into searchtowns(id, name) values ('Maasdonk gem bestuur','Maasdonk gem bestuur');
insert into searchtowns(id, name) values ('Maasdriel gem bestuur','Maasdriel gem bestuur');
insert into searchtowns(id, name) values ('Maastricht Airport','Maastricht Airport');
insert into searchtowns(id, name) values ('Maasvlakte rt','Maasvlakte rt');
insert into searchtowns(id, name) values ('Mariënberg','Mariënberg');
insert into searchtowns(id, name) values ('Mariënheem','Mariënheem');
insert into searchtowns(id, name) values ('Marle gem Olst-Wijhe','Marle gem Olst-Wijhe');
insert into searchtowns(id, name) values ('Martin Luther Kingpark Amsterdam','Martin Luther Kingpark Amsterdam');
insert into searchtowns(id, name) values ('Marwijksoord','Marwijksoord');
insert into searchtowns(id, name) values ('Melissant','Melissant');
insert into searchtowns(id, name) values ('Menaldumadeel gem bestuur','Menaldumadeel gem bestuur');
insert into searchtowns(id, name) values ('Menterwolde gem bestuur','Menterwolde gem bestuur');
insert into searchtowns(id, name) values ('Mesch','Mesch');
insert into searchtowns(id, name) values ('Mijzen','Mijzen');
insert into searchtowns(id, name) values ('Millingen Legerplaats','Millingen Legerplaats');
insert into searchtowns(id, name) values ('Moerkapelle','Moerkapelle');
insert into searchtowns(id, name) values ('Molenhoek lb','Molenhoek lb');
insert into searchtowns(id, name) values ('Montferland gem bestuur','Montferland gem bestuur');
insert into searchtowns(id, name) values ('Munnekezijl','Munnekezijl');
insert into searchtowns(id, name) values ('Nes gem Boarnsterhim','Nes gem Boarnsterhim');
insert into searchtowns(id, name) values ('Nes gem Dongeradeel','Nes gem Dongeradeel');
insert into searchtowns(id, name) values ('Nesserluis','Nesserluis');
insert into searchtowns(id, name) values ('Niekerk gem De Marne','Niekerk gem De Marne');
insert into searchtowns(id, name) values ('Niekerk gem Grootegast','Niekerk gem Grootegast');
insert into searchtowns(id, name) values ('Nieuw Einde','Nieuw Einde');
insert into searchtowns(id, name) values ('Nieuw Scheemda','Nieuw Scheemda');
insert into searchtowns(id, name) values ('Nieuw en St Joosland','Nieuw en St Joosland');
insert into searchtowns(id, name) values ('Nieuwdorp zld','Nieuwdorp zld');
insert into searchtowns(id, name) values ('Nieuwe Pekela','Nieuwe Pekela');
insert into searchtowns(id, name) values ('Nieuwerkerk zld','Nieuwerkerk zld');
insert into searchtowns(id, name) values ('Nieuweschild','Nieuweschild');
insert into searchtowns(id, name) values ('Nieuwland','Nieuwland');
insert into searchtowns(id, name) values ('Nieuwlande gem Coevorden','Nieuwlande gem Coevorden');
insert into searchtowns(id, name) values ('Nijbroek','Nijbroek');
insert into searchtowns(id, name) values ('Nijefurd gem bestuur','Nijefurd gem bestuur');
insert into searchtowns(id, name) values ('Nijetrijne','Nijetrijne');
insert into searchtowns(id, name) values ('Nijkerk gld','Nijkerk gld');
insert into searchtowns(id, name) values ('Nijnsel','Nijnsel');
insert into searchtowns(id, name) values ('Nooitgedacht','Nooitgedacht');
insert into searchtowns(id, name) values ('Noorddijk gn','Noorddijk gn');
insert into searchtowns(id, name) values ('Noordeinde gld','Noordeinde gld');
insert into searchtowns(id, name) values ('Noordoostpolder gem bestuur','Noordoostpolder gem bestuur');
insert into searchtowns(id, name) values ('Noordwijk gn','Noordwijk gn');
insert into searchtowns(id, name) values ('Noordwolde gn','Noordwolde gn');
insert into searchtowns(id, name) values ('Nuland','Nuland');
insert into searchtowns(id, name) values ('Ohé en Laak','Ohé en Laak');
insert into searchtowns(id, name) values ('Oldebroek Legerplaats','Oldebroek Legerplaats');
insert into searchtowns(id, name) values ('Onderbanken  gem bestuur','Onderbanken  gem bestuur');
insert into searchtowns(id, name) values ('Onderste Locht','Onderste Locht');
insert into searchtowns(id, name) values ('Ooij gem Ubbergen','Ooij gem Ubbergen');
insert into searchtowns(id, name) values ('Ooijen lb','Ooijen lb');
insert into searchtowns(id, name) values ('Ooltgensplaat','Ooltgensplaat');
insert into searchtowns(id, name) values ('Oost lb','Oost lb');
insert into searchtowns(id, name) values ('Oost- West- en Middelbeers','Oost- West- en Middelbeers');
insert into searchtowns(id, name) values ('Oosterend gem Littenseradiel','Oosterend gem Littenseradiel');
insert into searchtowns(id, name) values ('Oosterhout gem Nijmegen','Oosterhout gem Nijmegen');
insert into searchtowns(id, name) values ('Oosterhout gld','Oosterhout gld');
insert into searchtowns(id, name) values ('Oosterland zld','Oosterland zld');
insert into searchtowns(id, name) values ('Oosterpark Amsterdam','Oosterpark Amsterdam');
insert into searchtowns(id, name) values ('Oosterwolde gld','Oosterwolde gld');
insert into searchtowns(id, name) values ('Oostflakkee gem bestuur','Oostflakkee gem bestuur');
insert into searchtowns(id, name) values ('Oostknollendam','Oostknollendam');
insert into searchtowns(id, name) values ('Oostrum lb','Oostrum lb');
insert into searchtowns(id, name) values ('Ooststellingwerf gem bestuur','Ooststellingwerf gem bestuur');
insert into searchtowns(id, name) values ('Oostvoorne','Oostvoorne');
insert into searchtowns(id, name) values ('Oostwold gem Leek','Oostwold gem Leek');
insert into searchtowns(id, name) values ('Oostwold gem Oldambt','Oostwold gem Oldambt');
insert into searchtowns(id, name) values ('Ooy gem Zevenaar','Ooy gem Zevenaar');
insert into searchtowns(id, name) values ('Opende','Opende');
insert into searchtowns(id, name) values ('Oploo','Oploo');
insert into searchtowns(id, name) values ('Opsterland gem bestuur','Opsterland gem bestuur');
insert into searchtowns(id, name) values ('Ossenwaard ut','Ossenwaard ut');
insert into searchtowns(id, name) values ('Oudega gem Gaasterlân-Sleat','Oudega gem Gaasterlân-Sleat');
insert into searchtowns(id, name) values ('Oudega gem Smallingerland','Oudega gem Smallingerland');
insert into searchtowns(id, name) values ('Oudega gem Wymbritseradiel','Oudega gem Wymbritseradiel');
insert into searchtowns(id, name) values ('Pernis rt','Pernis rt');
insert into searchtowns(id, name) values ('Poortvliet','Poortvliet');
insert into searchtowns(id, name) values ('Radewijk','Radewijk');
insert into searchtowns(id, name) values ('Ramspol','Ramspol');
insert into searchtowns(id, name) values ('Reahûs','Reahûs');
insert into searchtowns(id, name) values ('Reiderland gem bestuur','Reiderland gem bestuur');
insert into searchtowns(id, name) values ('Reimerswaal gem bestuur','Reimerswaal gem bestuur');
insert into searchtowns(id, name) values ('Rembrandt Huis','Rembrandt Huis');
insert into searchtowns(id, name) values ('Rembrandthuis Amsterdam','Rembrandthuis Amsterdam');
insert into searchtowns(id, name) values ('Rembrandtpark Amsterdam','Rembrandtpark Amsterdam');
insert into searchtowns(id, name) values ('Ressen gem Nijmegen','Ressen gem Nijmegen');
insert into searchtowns(id, name) values ('Retranchement','Retranchement');
insert into searchtowns(id, name) values ('Rhederveld gem Bellingwedde','Rhederveld gem Bellingwedde');
insert into searchtowns(id, name) values ('Rhederveld gem Vlagtwedde','Rhederveld gem Vlagtwedde');
insert into searchtowns(id, name) values ('Rijkevoort-de Walsert','Rijkevoort-de Walsert');
insert into searchtowns(id, name) values ('Rijnwoude gem bestuur','Rijnwoude gem bestuur');
insert into searchtowns(id, name) values ('Rijswijk gld','Rijswijk gld');
insert into searchtowns(id, name) values ('Roerdalen gem bestuur','Roerdalen gem bestuur');
insert into searchtowns(id, name) values ('Roodeschool','Roodeschool');
insert into searchtowns(id, name) values ('Rooth gem Maasbree','Rooth gem Maasbree');
insert into searchtowns(id, name) values ('Rossum gld','Rossum gld');
insert into searchtowns(id, name) values ('Rotterdam Albrandswaard','Rotterdam Albrandswaard');
insert into searchtowns(id, name) values ('Rottum gn','Rottum gn');
insert into searchtowns(id, name) values ('Rumpt','Rumpt');
insert into searchtowns(id, name) values ('S-Gravenhagea','S-Gravenhagea');
insert into searchtowns(id, name) values ('Schagerwaard','Schagerwaard');
insert into searchtowns(id, name) values ('Schandelen','Schandelen');
insert into searchtowns(id, name) values ('Scharsterland gem bestuur','Scharsterland gem bestuur');
insert into searchtowns(id, name) values ('Scherpenzeel gld','Scherpenzeel gld');
insert into searchtowns(id, name) values ('Schilberg gem Margraten','Schilberg gem Margraten');
insert into searchtowns(id, name) values ('Schilberg gem Wittem','Schilberg gem Wittem');
insert into searchtowns(id, name) values ('Schiphol-Centrum','Schiphol-Centrum');
insert into searchtowns(id, name) values ('Schiphol-Oost','Schiphol-Oost');
insert into searchtowns(id, name) values ('Schoorldam gem Bergen nh','Schoorldam gem Bergen nh');
insert into searchtowns(id, name) values ('Schoorldam gem Harenkarspel','Schoorldam gem Harenkarspel');
insert into searchtowns(id, name) values ('Schouwen Duiveland gem bestuur','Schouwen Duiveland gem bestuur');
insert into searchtowns(id, name) values ('Serooskerke Walcheren','Serooskerke Walcheren');
insert into searchtowns(id, name) values ('Siebengewald','Siebengewald');
insert into searchtowns(id, name) values ('Sinderen gem Oude IJsselstreek','Sinderen gem Oude IJsselstreek');
insert into searchtowns(id, name) values ('Skarsterlân gem bestuur','Skarsterlân gem bestuur');
insert into searchtowns(id, name) values ('Smallingerland gem bestuur','Smallingerland gem bestuur');
insert into searchtowns(id, name) values ('Soestdijk gem Baarn','Soestdijk gem Baarn');
insert into searchtowns(id, name) values ('Soestdijk gem Soest','Soestdijk gem Soest');
insert into searchtowns(id, name) values ('Spaarndam-West','Spaarndam-West');
insert into searchtowns(id, name) values ('Spijk gem Lingewaal','Spijk gem Lingewaal');
insert into searchtowns(id, name) values ('Spijk gld','Spijk gld');
insert into searchtowns(id, name) values ('Spijk gn','Spijk gn');
insert into searchtowns(id, name) values ('St Agatha','St Agatha');
insert into searchtowns(id, name) values ('St Anna ter Muiden','St Anna ter Muiden');
insert into searchtowns(id, name) values ('St Annaland','St Annaland');
insert into searchtowns(id, name) values ('St Annaparochie','St Annaparochie');
insert into searchtowns(id, name) values ('St Annen','St Annen');
insert into searchtowns(id, name) values ('St Anthonis','St Anthonis');
insert into searchtowns(id, name) values ('St Geertruid','St Geertruid');
insert into searchtowns(id, name) values ('St Hubert','St Hubert');
insert into searchtowns(id, name) values ('St Isidorushoeve','St Isidorushoeve');
insert into searchtowns(id, name) values ('St Jacobiparochie','St Jacobiparochie');
insert into searchtowns(id, name) values ('St Jansklooster','St Jansklooster');
insert into searchtowns(id, name) values ('St Jansteen','St Jansteen');
insert into searchtowns(id, name) values ('St Johannesga','St Johannesga');
insert into searchtowns(id, name) values ('St Joost','St Joost');
insert into searchtowns(id, name) values ('St Kruis','St Kruis');
insert into searchtowns(id, name) values ('St Laurens','St Laurens');
insert into searchtowns(id, name) values ('St Maarten','St Maarten');
insert into searchtowns(id, name) values ('St Maartensbrug','St Maartensbrug');
insert into searchtowns(id, name) values ('St Maartensdijk','St Maartensdijk');
insert into searchtowns(id, name) values ('St Maartensvlotbrug','St Maartensvlotbrug');
insert into searchtowns(id, name) values ('St Maartenszee','St Maartenszee');
insert into searchtowns(id, name) values ('St Michielsgestel','St Michielsgestel');
insert into searchtowns(id, name) values ('St Nicolaasga','St Nicolaasga');
insert into searchtowns(id, name) values ('St Odiliënberg','St Odiliënberg');
insert into searchtowns(id, name) values ('St Oedenrode','St Oedenrode');
insert into searchtowns(id, name) values ('St Pancras','St Pancras');
insert into searchtowns(id, name) values ('St Philipsland','St Philipsland');
insert into searchtowns(id, name) values ('St Willebrord','St Willebrord');
insert into searchtowns(id, name) values ('Starnmeer','Starnmeer');
insert into searchtowns(id, name) values ('Startenhuizen Lopp','Startenhuizen Lopp');
insert into searchtowns(id, name) values ('Station Haarlem','Station Haarlem');
insert into searchtowns(id, name) values ('Stavenisse','Stavenisse');
insert into searchtowns(id, name) values ('Steenbergen gem Noordenveld','Steenbergen gem Noordenveld');
insert into searchtowns(id, name) values ('Steenbergen gem Zuidwolde dr','Steenbergen gem Zuidwolde dr');
insert into searchtowns(id, name) values ('Steenwijkerland gem bestuur','Steenwijkerland gem bestuur');
insert into searchtowns(id, name) values ('Stein lb','Stein lb');
insert into searchtowns(id, name) values ('Stokkum gld','Stokkum gld');
insert into searchtowns(id, name) values ('Stoutenburg Noord','Stoutenburg Noord');
insert into searchtowns(id, name) values ('Strijbeek','Strijbeek');
insert into searchtowns(id, name) values ('Suwâld','Suwâld');
insert into searchtowns(id, name) values ('Swifterbant','Swifterbant');
insert into searchtowns(id, name) values ('Tergracht gem Ferwerderadiel','Tergracht gem Ferwerderadiel');
insert into searchtowns(id, name) values ('Tergracht gem Tietjerksteradeel','Tergracht gem Tietjerksteradeel');
insert into searchtowns(id, name) values ('Tergrêft gem Ferwerderadiel','Tergrêft gem Ferwerderadiel');
insert into searchtowns(id, name) values ('Thij','Thij');
insert into searchtowns(id, name) values ('Tietjerksteradeel gem bestuur','Tietjerksteradeel gem bestuur');
insert into searchtowns(id, name) values ('Tongeren gld','Tongeren gld');
insert into searchtowns(id, name) values ('Tweede Exloërmond','Tweede Exloërmond');
insert into searchtowns(id, name) values ('Tytsjerksteradiel gem bestuur','Tytsjerksteradiel gem bestuur');
insert into searchtowns(id, name) values ('Ulvenhout ac','Ulvenhout ac');
insert into searchtowns(id, name) values ('Ursem gem Wester-Koggenland','Ursem gem Wester-Koggenland');
insert into searchtowns(id, name) values ('Usquert','Usquert');
insert into searchtowns(id, name) values ('Valkenburg lb','Valkenburg lb');
insert into searchtowns(id, name) values ('Valthermond','Valthermond');
insert into searchtowns(id, name) values ('Varssel','Varssel');
insert into searchtowns(id, name) values ('Varsselder-Veldhunten','Varsselder-Veldhunten');
insert into searchtowns(id, name) values ('Velp gld','Velp gld');
insert into searchtowns(id, name) values ('Verwolde','Verwolde');
insert into searchtowns(id, name) values ('Vledderveen gn','Vledderveen gn');
insert into searchtowns(id, name) values ('Vondelingenplaat rt','Vondelingenplaat rt');
insert into searchtowns(id, name) values ('Voorst gem Voorst','Voorst gem Voorst');
insert into searchtowns(id, name) values ('Vrouwenparochie','Vrouwenparochie');
insert into searchtowns(id, name) values ('Waaksens gem Littenseradiel','Waaksens gem Littenseradiel');
insert into searchtowns(id, name) values ('Waaxens gem Dongeradeel','Waaxens gem Dongeradeel');
insert into searchtowns(id, name) values ('Waaxens gem Littenseradiel','Waaxens gem Littenseradiel');
insert into searchtowns(id, name) values ('Warder','Warder');
insert into searchtowns(id, name) values ('Waterland gem bestuur','Waterland gem bestuur');
insert into searchtowns(id, name) values ('Weerselo','Weerselo');
insert into searchtowns(id, name) values ('Well gld','Well gld');
insert into searchtowns(id, name) values ('Well lb','Well lb');
insert into searchtowns(id, name) values ('Wenum Wiesel','Wenum Wiesel');
insert into searchtowns(id, name) values ('Wesepe','Wesepe');
insert into searchtowns(id, name) values ('Westerlee gn','Westerlee gn');
insert into searchtowns(id, name) values ('Westhoek','Westhoek');
insert into searchtowns(id, name) values ('Westknollendam','Westknollendam');
insert into searchtowns(id, name) values ('Westmaas','Westmaas');
insert into searchtowns(id, name) values ('Weststellingwerf gem bestuur','Weststellingwerf gem bestuur');
insert into searchtowns(id, name) values ('Wieringen gem bestuur','Wieringen gem bestuur');
insert into searchtowns(id, name) values ('Wieringermeer gem bestuur','Wieringermeer gem bestuur');
insert into searchtowns(id, name) values ('Wieringerwerf','Wieringerwerf');
insert into searchtowns(id, name) values ('Wierum','Wierum');
insert into searchtowns(id, name) values ('Wijmbritseradeel gem bestuur','Wijmbritseradeel gem bestuur');
insert into searchtowns(id, name) values ('Wildenborch','Wildenborch');
insert into searchtowns(id, name) values ('Wildervangsterdallen','Wildervangsterdallen');
insert into searchtowns(id, name) values ('Winsum gn','Winsum gn');
insert into searchtowns(id, name) values ('Winterswijk Ratum','Winterswijk Ratum');
insert into searchtowns(id, name) values ('Wirdum gn','Wirdum gn');
insert into searchtowns(id, name) values ('Wonseradeel gem bestuur','Wonseradeel gem bestuur');
insert into searchtowns(id, name) values ('Wymbritseradiel gem bestuur','Wymbritseradiel gem bestuur');
insert into searchtowns(id, name) values ('Ysselsteyn lb','Ysselsteyn lb');
insert into searchtowns(id, name) values ('Zandberg dr','Zandberg dr');
insert into searchtowns(id, name) values ('Zederik gem bestuur','Zederik gem bestuur');
insert into searchtowns(id, name) values ('Zeevang gem bestuur','Zeevang gem bestuur');
insert into searchtowns(id, name) values ('Zeijerveen','Zeijerveen');
insert into searchtowns(id, name) values ('Zeijerveld','Zeijerveld');
insert into searchtowns(id, name) values ('Zevenbergschen Hoek Drimmelen','Zevenbergschen Hoek Drimmelen');
insert into searchtowns(id, name) values ('Zevenhuizen gn','Zevenhuizen gn');
insert into searchtowns(id, name) values ('Zijpe gem bestuur','Zijpe gem bestuur');
insert into searchtowns(id, name) values ('Zuidveld','Zuidveld');
insert into searchtowns(id, name) values ('Zuidwolde gn','Zuidwolde gn');